### ISSUE TITLE
Relayer never Active / Always "Starting..."

### ISSUE THREAD

**Issue by Aptosuper** [dymensionxyz/roller#296] opened 2023-07-19 19:22 UTC
### Roller version

v0.1.13

### OS

unbuntu 22.04

### Processor Architecture

x86 Intel CX41 (hetzner vps)

### Others

Git commit: 56ac9b7f22ce6f54d7f81bd88dfe69028d58a0bf

Actual status : 
![Sans titre](https://github.com/dymensionxyz/roller/assets/111451773/9d888224-0793-42ca-9c53-eebf70776925)

When i try to start the relayer : 

![image](https://github.com/dymensionxyz/roller/assets/111451773/85a687d2-a03e-4ab5-879a-62ef250f5edf)

### Steps to reproduce it

Run the Rollapp

### Expected result

Relayer "Active"

### Actual result

Relayer still "Starting..."

### Notes

my discord id : superxxxxx

**Comment by omritoptix** [comment] 2023-07-20 10:31
Thank you @Aptosuper. Can you please post the full relayer log file here?

**Comment by mtsitrin** [comment] 2023-07-31 06:49
Can't reproduce, and more info needed.

anyway relayer flow refactored in upcoming release.

Closing for now.

**Closed by mtsitrin** 2023-07-31 06:49 UTC
Labels: bug, C:relayer
