### ISSUE TITLE
roller tx register error

### ISSUE THREAD

**Issue by keienWang** [dymensionxyz/roller#629] opened 2023-12-11 06:33 UTC
### Roller version

Roller version v1.0.0-beta

### OS

ubuntu 22:04

### Processor Architecture

rollapp register faild

### Others

<img width="763" alt="image" src="https://github.com/dymensionxyz/roller/assets/42377006/7d7e0b2d-6683-4c0f-9f76-0f7e2e6b4222">

### Steps to reproduce it

root@dymension-3:~# roller tx register
💈 errUnknownField "*types.MsgCreateRollapp": {TagNum: 8, WireType:"bytes"}: tx parse error
root@dymension-3:~# roller version
💈 Roller version v1.0.0-beta
💈 Build time: 2023-12-10T17:58:27+0000"
💈 Git commit: 3be9ca6177456a645d7fd0966765e69358605806

### Expected result

Rollapp 'xxx_101-1' has been successfully registered on the hub.

### Actual result

 errUnknownField "*types.MsgCreateRollapp": {TagNum: 8, WireType:"bytes"}: tx parse error

**Comment by omritoptix** [comment] 2023-12-14 11:00
We've updated the hub with a breaking change so you must use the latest version of roller (v1.0.2-beta)

**Comment by keienWang** [comment] 2023-12-20 06:41
<img width="897" alt="image" src="https://github.com/dymensionxyz/roller/assets/42377006/d3391466-4d76-4dd9-9b1c-fc1c8696789a">
I updated the latest version and successfully started the node and ran the following commands. The results were all running, but there was still an RPC that could not connect.

**Comment by keienWang** [comment] 2023-12-20 06:44
commands：
sudo systemctl status da-light-client
sudo systemctl status sequencer
sudo systemctl status relayer
result：
<img width="546" alt="image" src="https://github.com/dymensionxyz/roller/assets/42377006/1398b3b8-af01-4aed-a1a2-c79b8ca7eea2">
<img width="677" alt="image" src="https://github.com/dymensionxyz/roller/assets/42377006/66f099b7-d178-4050-8c71-1f3a94b1baf0">
<img width="697" alt="image" src="https://github.com/dymensionxyz/roller/assets/42377006/eaf6c42e-3a05-4314-a6a2-604787ce8056">

**Comment by artemijspavlovs** [comment] 2024-08-18 10:24
closing, old.

please reopen if the issue is still relevant

**Closed by artemijspavlovs** 2024-08-18 10:24 UTC
Labels: bug
