### ISSUE TITLE
[Feature Request]: Sir, My portal address that is connected is wrong but eligible this wrong address . What can i do now

### ISSUE THREAD

**Issue by kabirgbonline** [dymensionxyz/roller#708] opened 2024-02-06 17:37 UTC
### Implementation ideas

Sir i join this rollapp by 0x4A9C0b1C3a97603E2B03fdEBB3C24067E695abdB this. After connection i saw this 0x4f70be5b4c055be610846d310378cf64163b949e . But i do not know how this address generate. I am eligible by this  address 0x4f70be5b4c055be610846d310378cf64163b949e .How to solve this problem.

**Comment by Chuuuqs** [comment] 2024-02-08 11:04
Same issue here, wondering if they got back to you?
I think the issue is from the firebase change.
Was initially (dymension-3f01e now dymension-mainnet)

**Comment by artemijspavlovs** [comment] 2024-08-18 09:33
closing, this is not related to roller.

**Closed by artemijspavlovs** 2024-08-18 09:33 UTC
Labels: enhancement
