### ISSUE TITLE
unable to send ibc transfer

### ISSUE THREAD

**Issue by thagunslinger** [dymensionxyz/roller#284] opened 2023-07-17 11:45 UTC
### Roller version

roller version devnet_304-1

### OS

https://docs.dymension.xyz/build/quick-start/roller-quick/run

### Processor Architecture

6 vCPU Cores 16 GB RAM 400gb ssd

### Others

n/a

### Steps to reproduce it

rollapp_evm tx ibc-transfer transfer transfer channel-0 dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz 1000000000000000000uRAX --from rollapp_sequencer --keyring-backend test --home ~/.roller/rollapp --broadcast-mode block

$balances dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz gunslinger_1234-2

rollapp_evm q tx 917143324C100C260D39CB176EC848788AF87D5535DDB4CED1421EE01FDCE00A

$balances dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz gunslinger_1234-2

### Expected result

the transaction to work, and the faucet to be filled

### Actual result

faucet remains empty

### Relevant log output

```Shell
rollapp_evm q tx 917143324C100C260D39CB176EC848788AF87D5535DDB4CED1421EE01FDCE00A
code: 0
codespace: ""
data: 12370A312F6962632E6170706C69636174696F6E732E7472616E736665722E76312E4D73675472616E73666572526573706F6E736512020804
events:
- attributes:
  - index: true
    key: YWNjX3NlcQ==
    value: ZXRobTEwY2plcGdtbXl3bnhsNDl0ZGFrNjRhcXY1bHdoZHlweWtsd2tyaC80
  type: tx
- attributes:
  - index: true
    key: c2lnbmF0dXJl
    value: RXlIRkY3Um15aFhONzBPbmFJcjQ3ck56dlFscW5sSmFJMEw5dXlHbFFoMExIL0g0NkF6azhWenVLaG1YajlDRVhhazRTTFFvVkhBM0RPOHQ4TE5QTWdFPQ==
  type: tx
- attributes:
  - index: true
    key: YWN0aW9u
    value: L2liYy5hcHBsaWNhdGlvbnMudHJhbnNmZXIudjEuTXNnVHJhbnNmZXI=
  type: message
- attributes:
  - index: true
    key: c3BlbmRlcg==
    value: ZXRobTEwY2plcGdtbXl3bnhsNDl0ZGFrNjRhcXY1bHdoZHlweWtsd2tyaA==
  - index: true
    key: YW1vdW50
    value: MTAwMDAwMDAwMDAwMDAwMDAwMHVSQVg=
  type: coin_spent
- attributes:
  - index: true
    key: cmVjZWl2ZXI=
    value: ZXRobTFhNTN1ZGF6eThheXVmdnkwczQzNHBmd2pjZWR6cXYzNGR6djhndg==
  - index: true
    key: YW1vdW50
    value: MTAwMDAwMDAwMDAwMDAwMDAwMHVSQVg=
  type: coin_received
- attributes:
  - index: true
    key: cmVjaXBpZW50
    value: ZXRobTFhNTN1ZGF6eThheXVmdnkwczQzNHBmd2pjZWR6cXYzNGR6djhndg==
  - index: true
    key: c2VuZGVy
    value: ZXRobTEwY2plcGdtbXl3bnhsNDl0ZGFrNjRhcXY1bHdoZHlweWtsd2tyaA==
  - index: true
    key: YW1vdW50
    value: MTAwMDAwMDAwMDAwMDAwMDAwMHVSQVg=
  type: transfer
- attributes:
  - index: true
    key: c2VuZGVy
    value: ZXRobTEwY2plcGdtbXl3bnhsNDl0ZGFrNjRhcXY1bHdoZHlweWtsd2tyaA==
  type: message
- attributes:
  - index: true
    key: cGFja2V0X2RhdGE=
    value: eyJhbW91bnQiOiIxMDAwMDAwMDAwMDAwMDAwMDAwIiwiZGVub20iOiJ1UkFYIiwicmVjZWl2ZXIiOiJkeW0xMmFkNGx1eDM2bHRhN2Q3NXYydzZqZTJ5Mzg2eTlzNXhwNjU4cHoiLCJzZW5kZXIiOiJldGhtMTBjamVwZ21teXdueGw0OXRkYWs2NGFxdjVsd2hkeXB5a2x3a3JoIn0=
  - index: true
    key: cGFja2V0X2RhdGFfaGV4
    value: N2IyMjYxNmQ2Zjc1NmU3NDIyM2EyMjMxMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMjIyYzIyNjQ2NTZlNmY2ZDIyM2EyMjc1NTI0MTU4MjIyYzIyNzI2NTYzNjU2OTc2NjU3MjIyM2EyMjY0Nzk2ZDMxMzI2MTY0MzQ2Yzc1NzgzMzM2NmM3NDYxMzc2NDM3MzU3NjMyNzczNjZhNjUzMjc5MzMzODM2NzkzOTczMzU3ODcwMzYzNTM4NzA3YTIyMmMyMjczNjU2ZTY0NjU3MjIyM2EyMjY1NzQ2ODZkMzEzMDYzNmE2NTcwNjc2ZDZkNzk3NzZlNzg2YzM0Mzk3NDY0NjE2YjM2MzQ2MTcxNzYzNTZjNzc2ODY0Nzk3MDc5NmI2Yzc3NmI3MjY4MjI3ZA==
  - index: true
    key: cGFja2V0X3RpbWVvdXRfaGVpZ2h0
    value: MS0yNzgxMTA=
  - index: true
    key: cGFja2V0X3RpbWVvdXRfdGltZXN0YW1w
    value: MTY4OTUxOTcwNzk5MDc1MzU0Mw==
  - index: true
    key: cGFja2V0X3NlcXVlbmNl
    value: NA==
  - index: true
    key: cGFja2V0X3NyY19wb3J0
    value: dHJhbnNmZXI=
  - index: true
    key: cGFja2V0X3NyY19jaGFubmVs
    value: Y2hhbm5lbC0w
  - index: true
    key: cGFja2V0X2RzdF9wb3J0
    value: dHJhbnNmZXI=
  - index: true
    key: cGFja2V0X2RzdF9jaGFubmVs
    value: Y2hhbm5lbC01MQ==
  - index: true
    key: cGFja2V0X2NoYW5uZWxfb3JkZXJpbmc=
    value: T1JERVJfVU5PUkRFUkVE
  - index: true
    key: cGFja2V0X2Nvbm5lY3Rpb24=
    value: Y29ubmVjdGlvbi0w
  type: send_packet
- attributes:
  - index: true
    key: bW9kdWxl
    value: aWJjX2NoYW5uZWw=
  type: message
- attributes:
  - index: true
    key: c2VuZGVy
    value: ZXRobTEwY2plcGdtbXl3bnhsNDl0ZGFrNjRhcXY1bHdoZHlweWtsd2tyaA==
  - index: true
    key: cmVjZWl2ZXI=
    value: ZHltMTJhZDRsdXgzNmx0YTdkNzV2Mnc2amUyeTM4Nnk5czV4cDY1OHB6
  type: ibc_transfer
- attributes:
  - index: true
    key: bW9kdWxl
    value: dHJhbnNmZXI=
  type: message
gas_used: "72561"
gas_wanted: "200000"
height: "36872"
info: ""
logs:
- events:
  - attributes:
    - key: receiver
      value: ethm1a53udazy8ayufvy0s434pfwjcedzqv34dzv8gv
    - key: amount
      value: 1000000000000000000uRAX
    type: coin_received
  - attributes:
    - key: spender
      value: ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh
    - key: amount
      value: 1000000000000000000uRAX
    type: coin_spent
  - attributes:
    - key: sender
      value: ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh
    - key: receiver
      value: dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz
    type: ibc_transfer
  - attributes:
    - key: action
      value: /ibc.applications.transfer.v1.MsgTransfer
    - key: sender
      value: ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh
    - key: module
      value: ibc_channel
    - key: module
      value: transfer
    type: message
  - attributes:
    - key: packet_data
      value: '{"amount":"1000000000000000000","denom":"uRAX","receiver":"dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz","sender":"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh"}'
    - key: packet_data_hex
      value: 7b22616d6f756e74223a2231303030303030303030303030303030303030222c2264656e6f6d223a2275524158222c227265636569766572223a2264796d31326164346c757833366c746137643735763277366a653279333836793973357870363538707a222c2273656e646572223a226574686d3130636a6570676d6d79776e786c34397464616b3634617176356c7768647970796b6c776b7268227d
    - key: packet_timeout_height
      value: 1-278110
    - key: packet_timeout_timestamp
      value: "1689519707990753543"
    - key: packet_sequence
      value: "4"
    - key: packet_src_port
      value: transfer
    - key: packet_src_channel
      value: channel-0
    - key: packet_dst_port
      value: transfer
    - key: packet_dst_channel
      value: channel-51
    - key: packet_channel_ordering
      value: ORDER_UNORDERED
    - key: packet_connection
      value: connection-0
    type: send_packet
  - attributes:
    - key: recipient
      value: ethm1a53udazy8ayufvy0s434pfwjcedzqv34dzv8gv
    - key: sender
      value: ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh
    - key: amount
      value: 1000000000000000000uRAX
    type: transfer
  log: ""
  msg_index: 0
raw_log: '[{"msg_index":0,"events":[{"type":"coin_received","attributes":[{"key":"receiver","value":"ethm1a53udazy8ayufvy0s434pfwjcedzqv34dzv8gv"},{"key":"amount","value":"1000000000000000000uRAX"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh"},{"key":"amount","value":"1000000000000000000uRAX"}]},{"type":"ibc_transfer","attributes":[{"key":"sender","value":"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh"},{"key":"receiver","value":"dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz"}]},{"type":"message","attributes":[{"key":"action","value":"/ibc.applications.transfer.v1.MsgTransfer"},{"key":"sender","value":"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh"},{"key":"module","value":"ibc_channel"},{"key":"module","value":"transfer"}]},{"type":"send_packet","attributes":[{"key":"packet_data","value":"{\"amount\":\"1000000000000000000\",\"denom\":\"uRAX\",\"receiver\":\"dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz\",\"sender\":\"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh\"}"},{"key":"packet_data_hex","value":"7b22616d6f756e74223a2231303030303030303030303030303030303030222c2264656e6f6d223a2275524158222c227265636569766572223a2264796d31326164346c757833366c746137643735763277366a653279333836793973357870363538707a222c2273656e646572223a226574686d3130636a6570676d6d79776e786c34397464616b3634617176356c7768647970796b6c776b7268227d"},{"key":"packet_timeout_height","value":"1-278110"},{"key":"packet_timeout_timestamp","value":"1689519707990753543"},{"key":"packet_sequence","value":"4"},{"key":"packet_src_port","value":"transfer"},{"key":"packet_src_channel","value":"channel-0"},{"key":"packet_dst_port","value":"transfer"},{"key":"packet_dst_channel","value":"channel-51"},{"key":"packet_channel_ordering","value":"ORDER_UNORDERED"},{"key":"packet_connection","value":"connection-0"}]},{"type":"transfer","attributes":[{"key":"recipient","value":"ethm1a53udazy8ayufvy0s434pfwjcedzqv34dzv8gv"},{"key":"sender","value":"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh"},{"key":"amount","value":"1000000000000000000uRAX"}]}]}]'
timestamp: "2023-07-16T14:51:49Z"
tx:
  '@type': /cosmos.tx.v1beta1.Tx
  auth_info:
    fee:
      amount: []
      gas_limit: "200000"
      granter: ""
      payer: ""
    signer_infos:
    - mode_info:
        single:
          mode: SIGN_MODE_DIRECT
      public_key:
        '@type': /ethermint.crypto.v1.ethsecp256k1.PubKey
        key: ArJbi39X6h1A5kAh1VKmqUtt4x4TlUNZ89nMTSaB3RzQ
      sequence: "4"
    tip: null
  body:
    extension_options: []
    memo: ""
    messages:
    - '@type': /ibc.applications.transfer.v1.MsgTransfer
      memo: ""
      receiver: dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz
      sender: ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh
      source_channel: channel-0
      source_port: transfer
      timeout_height:
        revision_height: "278110"
        revision_number: "1"
      timeout_timestamp: "1689519707990753543"
      token:
        amount: "1000000000000000000"
        denom: uRAX
    non_critical_extension_options: []
    timeout_height: "0"
  signatures:
  - EyHFF7RmyhXN70OnaIr47rNzvQlqnlJaI0L9uyGlQh0LH/H46Azk8VzuKhmXj9CEXak4SLQoVHA3DO8t8LNPMgE=
txhash: 917143324C100C260D39CB176EC848788AF87D5535DDB4CED1421EE01FDCE00A
```

### Notes

i followed this doc: https://docs.dymension.xyz/build/quick-start/roller-quick/run

**Comment by omritoptix** [comment] 2023-07-18 11:18
thank you @thagunslinger . Can you please attach the relayer log file?

**Comment by thagunslinger** [comment] 2023-07-18 11:25
***@***.***:~/dymension# rollapp_evm tx ibc-transfer transfer transfer
channel-0 dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz
1000000000000000000uRAX --from rollapp_sequencer --keyring-backend test
--home ~/.roller/rollapp --broadcast-mode block
auth_info:
  fee:
    amount: []
    gas_limit: "200000"
    granter: ""
    payer: ""
  signer_infos: []
  tip: null
body:
  extension_options: []
  memo: ""
  messages:
  - ***@***.***': /ibc.applications.transfer.v1.MsgTransfer
    memo: ""
    receiver: dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz
    sender: ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh
    source_channel: channel-0
    source_port: transfer
    timeout_height:
      revision_height: "212177"
      revision_number: "1"
    timeout_timestamp: "1689187492713270056"
    token:
      amount: "1000000000000000000"
      denom: uRAX
  non_critical_extension_options: []
  timeout_height: "0"
signatures: []
confirm transaction before signing and broadcasting [y/N]: y
code: 0
codespace: ""
data:
12370A312F6962632E6170706C69636174696F6E732E7472616E736665722E76312E4D73675472616E73666572526573706F6E736512020803
events:
- attributes:
  - index: true
    key: YWNjX3NlcQ==
    value: ZXRobTEwY2plcGdtbXl3bnhsNDl0ZGFrNjRhcXY1bHdoZHlweWtsd2tyaC8z
  type: tx
- attributes:
  - index: true
    key: c2lnbmF0dXJl
    value:
eElFUVJOQWpqeUR2T21ieDllNUdULzR0MUVwVkNpRlV0ZzhuWEdTUWtWSTFYdGZ4cndLUldxS0Y4RkpRa0VvZC9MTUJtYWlWd1kvODF6VHNZMUVkZFFFPQ==
  type: tx
- attributes:
  - index: true
    key: YWN0aW9u
    value: L2liYy5hcHBsaWNhdGlvbnMudHJhbnNmZXIudjEuTXNnVHJhbnNmZXI=
  type: message
- attributes:
  - index: true
    key: c3BlbmRlcg==
    value: ZXRobTEwY2plcGdtbXl3bnhsNDl0ZGFrNjRhcXY1bHdoZHlweWtsd2tyaA==
  - index: true
    key: YW1vdW50
    value: MTAwMDAwMDAwMDAwMDAwMDAwMHVSQVg=
  type: coin_spent
- attributes:
  - index: true
    key: cmVjZWl2ZXI=
    value: ZXRobTFhNTN1ZGF6eThheXVmdnkwczQzNHBmd2pjZWR6cXYzNGR6djhndg==
  - index: true
    key: YW1vdW50
    value: MTAwMDAwMDAwMDAwMDAwMDAwMHVSQVg=
  type: coin_received
- attributes:
  - index: true
    key: cmVjaXBpZW50
    value: ZXRobTFhNTN1ZGF6eThheXVmdnkwczQzNHBmd2pjZWR6cXYzNGR6djhndg==
  - index: true
    key: c2VuZGVy
    value: ZXRobTEwY2plcGdtbXl3bnhsNDl0ZGFrNjRhcXY1bHdoZHlweWtsd2tyaA==
  - index: true
    key: YW1vdW50
    value: MTAwMDAwMDAwMDAwMDAwMDAwMHVSQVg=
  type: transfer
- attributes:
  - index: true
    key: c2VuZGVy
    value: ZXRobTEwY2plcGdtbXl3bnhsNDl0ZGFrNjRhcXY1bHdoZHlweWtsd2tyaA==
  type: message
- attributes:
  - index: true
    key: cGFja2V0X2RhdGE=
    value:
eyJhbW91bnQiOiIxMDAwMDAwMDAwMDAwMDAwMDAwIiwiZGVub20iOiJ1UkFYIiwicmVjZWl2ZXIiOiJkeW0xMmFkNGx1eDM2bHRhN2Q3NXYydzZqZTJ5Mzg2eTlzNXhwNjU4cHoiLCJzZW5kZXIiOiJldGhtMTBjamVwZ21teXdueGw0OXRkYWs2NGFxdjVsd2hkeXB5a2x3a3JoIn0=
  - index: true
    key: cGFja2V0X2RhdGFfaGV4
    value:
N2IyMjYxNmQ2Zjc1NmU3NDIyM2EyMjMxMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMzAzMDMwMjIyYzIyNjQ2NTZlNmY2ZDIyM2EyMjc1NTI0MTU4MjIyYzIyNzI2NTYzNjU2OTc2NjU3MjIyM2EyMjY0Nzk2ZDMxMzI2MTY0MzQ2Yzc1NzgzMzM2NmM3NDYxMzc2NDM3MzU3NjMyNzczNjZhNjUzMjc5MzMzODM2NzkzOTczMzU3ODcwMzYzNTM4NzA3YTIyMmMyMjczNjU2ZTY0NjU3MjIyM2EyMjY1NzQ2ODZkMzEzMDYzNmE2NTcwNjc2ZDZkNzk3NzZlNzg2YzM0Mzk3NDY0NjE2YjM2MzQ2MTcxNzYzNTZjNzc2ODY0Nzk3MDc5NmI2Yzc3NmI3MjY4MjI3ZA==
  - index: true
    key: cGFja2V0X3RpbWVvdXRfaGVpZ2h0
    value: MS0yMTIxNzc=
  - index: true
    key: cGFja2V0X3RpbWVvdXRfdGltZXN0YW1w
    value: MTY4OTE4NzQ5MjcxMzI3MDA1Ng==
  - index: true
    key: cGFja2V0X3NlcXVlbmNl
    value: Mw==
  - index: true
    key: cGFja2V0X3NyY19wb3J0
    value: dHJhbnNmZXI=
  - index: true
    key: cGFja2V0X3NyY19jaGFubmVs
    value: Y2hhbm5lbC0w
  - index: true
    key: cGFja2V0X2RzdF9wb3J0
    value: dHJhbnNmZXI=
  - index: true
    key: cGFja2V0X2RzdF9jaGFubmVs
    value: Y2hhbm5lbC01MQ==
  - index: true
    key: cGFja2V0X2NoYW5uZWxfb3JkZXJpbmc=
    value: T1JERVJfVU5PUkRFUkVE
  - index: true
    key: cGFja2V0X2Nvbm5lY3Rpb24=
    value: Y29ubmVjdGlvbi0w
  type: send_packet
- attributes:
  - index: true
    key: bW9kdWxl
    value: aWJjX2NoYW5uZWw=
  type: message
- attributes:
  - index: true
    key: c2VuZGVy
    value: ZXRobTEwY2plcGdtbXl3bnhsNDl0ZGFrNjRhcXY1bHdoZHlweWtsd2tyaA==
  - index: true
    key: cmVjZWl2ZXI=
    value: ZHltMTJhZDRsdXgzNmx0YTdkNzV2Mnc2amUyeTM4Nnk5czV4cDY1OHB6
  type: ibc_transfer
- attributes:
  - index: true
    key: bW9kdWxl
    value: dHJhbnNmZXI=
  type: message
gas_used: "72561"
gas_wanted: "200000"
height: "365"
info: ""
logs:
- events:
  - attributes:
    - key: receiver
      value: ethm1a53udazy8ayufvy0s434pfwjcedzqv34dzv8gv
    - key: amount
      value: 1000000000000000000uRAX
    type: coin_received
  - attributes:
    - key: spender
      value: ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh
    - key: amount
      value: 1000000000000000000uRAX
    type: coin_spent
  - attributes:
    - key: sender
      value: ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh
    - key: receiver
      value: dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz
    type: ibc_transfer
  - attributes:
    - key: action
      value: /ibc.applications.transfer.v1.MsgTransfer
    - key: sender
      value: ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh
    - key: module
      value: ibc_channel
    - key: module
      value: transfer
    type: message
  - attributes:
    - key: packet_data
      value:
'{"amount":"1000000000000000000","denom":"uRAX","receiver":"dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz","sender":"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh"}'
    - key: packet_data_hex
      value:
7b22616d6f756e74223a2231303030303030303030303030303030303030222c2264656e6f6d223a2275524158222c227265636569766572223a2264796d31326164346c757833366c746137643735763277366a653279333836793973357870363538707a222c2273656e646572223a226574686d3130636a6570676d6d79776e786c34397464616b3634617176356c7768647970796b6c776b7268227d
    - key: packet_timeout_height
      value: 1-212177
    - key: packet_timeout_timestamp
      value: "1689187492713270056"
    - key: packet_sequence
      value: "3"
    - key: packet_src_port
      value: transfer
    - key: packet_src_channel
      value: channel-0
    - key: packet_dst_port
      value: transfer
    - key: packet_dst_channel
      value: channel-51
    - key: packet_channel_ordering
      value: ORDER_UNORDERED
    - key: packet_connection
      value: connection-0
    type: send_packet
  - attributes:
    - key: recipient
      value: ethm1a53udazy8ayufvy0s434pfwjcedzqv34dzv8gv
    - key: sender
      value: ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh
    - key: amount
      value: 1000000000000000000uRAX
    type: transfer
  log: ""
  msg_index: 0
raw_log:
'[{"msg_index":0,"events":[{"type":"coin_received","attributes":[{"key":"receiver","value":"ethm1a53udazy8ayufvy0s434pfwjcedzqv34dzv8gv"},{"key":"amount","value":"1000000000000000000uRAX"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh"},{"key":"amount","value":"1000000000000000000uRAX"}]},{"type":"ibc_transfer","attributes":[{"key":"sender","value":"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh"},{"key":"receiver","value":"dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz"}]},{"type":"message","attributes":[{"key":"action","value":"/ibc.applications.transfer.v1.MsgTransfer"},{"key":"sender","value":"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh"},{"key":"module","value":"ibc_channel"},{"key":"module","value":"transfer"}]},{"type":"send_packet","attributes":[{"key":"packet_data","value":"{\"amount\":\"1000000000000000000\",\"denom\":\"uRAX\",\"receiver\":\"dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz\",\"sender\":\"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh\"}"},{"key":"packet_data_hex","value":"7b22616d6f756e74223a2231303030303030303030303030303030303030222c2264656e6f6d223a2275524158222c227265636569766572223a2264796d31326164346c757833366c746137643735763277366a653279333836793973357870363538707a222c2273656e646572223a226574686d3130636a6570676d6d79776e786c34397464616b3634617176356c7768647970796b6c776b7268227d"},{"key":"packet_timeout_height","value":"1-212177"},{"key":"packet_timeout_timestamp","value":"1689187492713270056"},{"key":"packet_sequence","value":"3"},{"key":"packet_src_port","value":"transfer"},{"key":"packet_src_channel","value":"channel-0"},{"key":"packet_dst_port","value":"transfer"},{"key":"packet_dst_channel","value":"channel-51"},{"key":"packet_channel_ordering","value":"ORDER_UNORDERED"},{"key":"packet_connection","value":"connection-0"}]},{"type":"transfer","attributes":[{"key":"recipient","value":"ethm1a53udazy8ayufvy0s434pfwjcedzqv34dzv8gv"},{"key":"sender","value":"ethm10cjepgmmywnxl49tdak64aqv5lwhdypyklwkrh"},{"key":"amount","value":"1000000000000000000uRAX"}]}]}]'
timestamp: ""
tx: null
txhash: 1F3584CE4B6F415640EDC1AC910627B0BB1496C59270F356FAC58EAE3526DA3C

**Comment by omritoptix** [comment] 2023-07-20 17:21
@thagunslinger thank you but I need the logfile. the log flle location should be printed in the roller output. usually under `~/.roller/relayer/relayer.log`

**Comment by thagunslinger** [comment] 2023-07-20 17:39
How to retrieve that?

**Comment by mtsitrin** [comment] 2023-07-24 10:48
Hi @thagunslinger 
Can u pls provide the Sequencer height and the Hub height
It's on the `roller run` output

**Comment by thagunslinger** [comment] 2023-07-24 13:29
Active, Height: 63373, Hub: 63349

**Comment by thagunslinger** [comment] 2023-07-28 01:36
any update on a fix for this?

**Comment by mtsitrin** [comment] 2023-07-28 13:56
From the log it seems the relayer fails to query the hub

Still happens? same error?

**Comment by thagunslinger** [comment] 2023-07-28 16:13
Well now I can't even get the roller dashboard to load

**Comment by thagunslinger** [comment] 2023-07-29 14:37
roller run
root@vmi1362023:~# tail -f .roller/relayer/relayer.log
Error: channel{} not found for [gunslinger_1234-2] -> client{07-tendermint-0}@connection{connection-0}
Error: channel{} not found for [gunslinger_1234-2] -> client{07-tendermint-0}@connection{connection-0}
ts=2023-07-29T14:28:51.486528Z lvl=info msg="Successful transaction" provider_type=cosmos chain_id=gunslinger_1234-2 gas_used=120422 fees= fee_payer=ethm1pj37vg0pdsmuayydjc0u52t4zgl3lcpz8xxeyw height=74231 msg_types=/ibc.core.client.v1.MsgUpdateClient tx_hash=0B2ACCFC59113A3595B4D0DB6875D69FBA681355D5C6B6A5F06F886CD030F91A
ts=2023-07-29T14:28:54.201955Z lvl=info msg="Successful transaction" provider_type=cosmos chain_id=devnet_304-1 gas_used=124385 fees=33544udym fee_payer=dym1tjug8trathnhrr2e5u7c7l24j33tj5f33jrpv9 height=499709 msg_types=/ibc.core.client.v1.MsgUpdateClient tx_hash=31C0814FEBD50FBDCCBF112E285959EFD6362B1A8CC142151E6D0F66387F1AF6
ts=2023-07-29T14:28:54.202160Z lvl=info msg="Clients updated" src_chain_id=gunslinger_1234-2 src_client=07-tendermint-0 src_height=2-74222 src_revision_height=74222 dst_chain_id=devnet_304-1 dst_client=01-dymint-64 dst_height=1-499708 dst_revision_height=499708
Error: channel{} not found for [gunslinger_1234-2] -> client{07-tendermint-0}@connection{connection-0}
Error: channel{} not found for [gunslinger_1234-2] -> client{07-tendermint-0}@connection{connection-0}
ts=2023-07-29T14:29:56.134858Z lvl=info msg="Successful transaction" provider_type=cosmos chain_id=gunslinger_1234-2 gas_used=120422 fees= fee_payer=ethm1pj37vg0pdsmuayydjc0u52t4zgl3lcpz8xxeyw height=74238 msg_types=/ibc.core.client.v1.MsgUpdateClient tx_hash=72B7480343AB6C76DB1A4D2300767F73B113ED74A893E97E3658C04BF15E9B26
ts=2023-07-29T14:29:59.554585Z lvl=info msg="Successful transaction" provider_type=cosmos chain_id=devnet_304-1 gas_used=124335 fees=33529udym fee_payer=dym1tjug8trathnhrr2e5u7c7l24j33tj5f33jrpv9 height=499722 msg_types=/ibc.core.client.v1.MsgUpdateClient tx_hash=CDC69C7C85C6A6F17E3EB06D4CFD194C61BFEFB8FE891A6DDA8DDFBF95D1D51B
ts=2023-07-29T14:29:59.554720Z lvl=info msg="Clients updated" src_chain_id=gunslinger_1234-2 src_client=07-tendermint-0 src_height=2-74234 src_revision_height=74234 dst_chain_id=devnet_304-1 dst_client=01-dymint-64 dst_height=1-499721 dst_revision_height=499721

**Comment by thagunslinger** [comment] 2023-07-29 14:39
![roller app 7 29 status](https://github.com/dymensionxyz/roller/assets/116745592/06136e77-5b6c-4461-a27b-b9d173482c2e)

**Comment by mtsitrin** [comment] 2023-07-30 06:58
It should be fixed in upcoming release (by #308)

u can try for now to run
` /usr/local/bin/roller_bins/rly --home ~/.roller/relayer tx link -t 300 hub-rollapp`

LMK if it worked

**Comment by mtsitrin** [comment] 2023-07-30 12:20
caused by #318

should be solved for now by restarting the sequencer

closing

**Closed by mtsitrin** 2023-07-30 12:20 UTC
Labels: bug, C:relayer

**Comment by thagunslinger** [comment] 2023-07-30 12:43
> 

/usr/local/bin/roller_bins/rly --home ~/.roller/relayer tx link -t 300 hub-rollapp
Error: time: missing unit in duration "300"

**Comment by mtsitrin** [comment] 2023-07-30 12:45
300s

**Comment by thagunslinger** [comment] 2023-07-30 12:51
> 300s

it worked! thank you, have been stuck on this for weeks
